# Generated by Django 5.2.15 on 2026-07-09 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_address_default"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
